name: CD Pipeline
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 54.236.50.150
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/fastapi-book-project
            
            # Pull latest changes
            git pull origin main
            source venv/bin/activate
            pip install --default-timeout=100 -r requirements.txt
            
            # Find and gracefully stop the old process
            OLD_PID=$(ps aux | grep '[g]unicorn' | awk '{print $2}')
            if [ ! -z "$OLD_PID" ]; then
              echo "Stopping old process $OLD_PID"
              kill -TERM $OLD_PID || true
              sleep 5
            fi
            
            # Start gunicorn with reduced workers and timeout
            gunicorn main:app \
              -w 2 \
              -k uvicorn.workers.UvicornWorker \
              -b 0.0.0.0:8000 \
              --timeout 120 \
              --access-logfile gunicorn-access.log \
              --error-logfile gunicorn-error.log \
              --log-level info \
              --daemon
            
            # Wait for new process to start
            sleep 5
            
            # Verify the application is running and serving the stage2 endpoint
            curl -s http://localhost:8000/stage2 || echo "Stage2 endpoint not available"
            
            # Reload nginx
            sudo systemctl reload nginx
