name: CD Pipeline
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 54.236.50.150
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/fastapi-book-project
            # Pull latest changes
            git pull origin main
            source venv/bin/activate
            pip install --default-timeout=100 -r requirements.txt
            
            # Force stop any running processes
            pkill -9 -f "gunicorn" || true
            pkill -9 -f "uvicorn" || true
            
            # Small delay to ensure processes are fully stopped
            sleep 2
            
            # Start the application with Gunicorn
            nohup gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 --access-logfile access.log --error-logfile error.log --daemon &
            
            # Wait for application to start
            sleep 5
            
            # Verify the application is running
            curl -s http://localhost:8000/healthcheck || echo "Application failed to start"
            
            # Reload nginx
            sudo systemctl reload nginx
